[package]
name = "ca1d"
authors = ["berquerant"]
version = "0.1.1"
edition = "2021"
readme = "README.md"
repository = "https://github.com/berquerant/ca1d"

[dependencies]
thiserror = "2.0"
anyhow = "1.0" 
chrono =  "0.4.42"
rand = "0.9.2"
clap = { version = "4.5.47", features = ["derive"] }
